apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: task-pv-claim
      initContainers:
        - name: init
          image: dmonakh/init_db_wp:v1
          volumeMounts:
              - mountPath: /var/www/html
                name: data
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql-wpmon.mysql.database.azure.com"
            - name: WORDPRESS_DB_NAME
              value: "test_manifest12"
            - name: WORDPRESS_DB_USER
              value: "monadmonsql@mysql-wpmon"
            - name: WORDPRESS_DB_PASSWORD
              value: "H@Sh1CoR3!"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: data
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sleep", "100"]     
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer